name: parse_server_dart
description: Parse Server Dart SDK.
version: 0.0.5
homepage: https://www.github.com/tgarm
author: simon <dingsm@gmail.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  path: ^1.4.1
  web_socket_channel: ^1.0.6
  http: ^0.11.3
  json_annotation: ^1.2.0
  flutter:
    sdk: flutter

